from calendar_planner.ui.stages.stage3_comparison import Stage3ComparisonFrame
from calendar_planner.ui.stages.stage4_participants import Stage4ParticipantsFrame
from calendar_planner.ui.stages.stage5_enrichment import Stage5EnrichmentFrame
from calendar_planner.ui.stages.stage6_creation import Stage6CreationFrame