from __future__ import annotations

from typing import Protocol

from calendar_planner.domain.models import CalendarEvent


class CalendarGateway(Protocol):
    def find_events(self, start_date: str, end_date: str) -> list[CalendarEvent]: ...
    def create_event(self, payload: dict, dry_run: bool = True) -> dict: ...
    def is_available(self) -> bool: ...
    def check_connection(self) -> dict: ...